### PR TITLE
Update readme to new build system

### PR DESCRIPTION
**Pull request by lionkor**
Now building is like 2 steps, so the readme reflects that now.

### CODE REVIEW

**Review by Lucky4Luuk — CHANGES_REQUESTED** [review]
Hey, this change seems pretty good to me, but there's a few notes I have:
- You have added build instructions, but the old build instructions still seem to be there. They are listed right underneath the runtime dependencies.
- The new build instructions don't list the requirements for building on Windows. I think this is worth writing down?
- In "Supported Operating Systems", it still links to the Prerequisites section, which is missing.

**Comment by Starystars67** [comment]
The points @Lucky4Luuk makes here are very good, Especially the steps for windows as that would be me :)

**Comment by lionkor** [comment]
Sorry @Lucky4Luuk if its not clear, but the windows build works the same. That was most of the point of this rewrite of the build system - ill fix the point about the old instructions.

**Comment by lionkor** [comment]
So @Starystars67 the same steps on windows, you just open the cmakelists with visual studio and it should just work

**Review by Lucky4Luuk — APPROVED** [review]
Looks good to me now, I have no more comments!

**Review by Lucky4Luuk — APPROVED** [review]

**Pull request merged**
