### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by lionkor**
Full rewrite of the server's structure

### CODE REVIEW

**Comment by Anonymous-275** [comment]
YEET

**Comment by lionkor** [comment]
Note that this merge does not signify a release point, and that the readme still needs to be updated in (almost) its entirety.

also please appreciate this
image
it's beautiful

**Comment by Anonymous-275** [comment]
Bellissimo! It's a big boi

**Comment by Anonymous-275** [comment]
RIP rewrite branch you will be missed

**Pull request merged**
