### PR TITLE
Rewrite Lua + New Lua Features + New Console + Commandline Args

### LINKED ISSUE #31: Add onExit
I suggest to add event when plugin is stopping so that stop plugin threads or close mysql connection

### LINKED ISSUE #35: Whitespace prepending message for the onChatMessage event.
I have found in the latest update of the server that there is prepended whitespace on the message parameter of the `onChatMessage` event in the Lua scripting interface.

Can we get this removed so that we do not need to trim the string before use?

### LINKED ISSUE #60: [Feature Request] 2.4.0: Show Quotes around strings in `print(table, ...)`
When printing a table, strings and numbers are indiscernible. 

Example:

```lua
local mytable = {
    a = "123",
    b = 123
}
```
`print(mytable)` gives:
```lua
[[table: 0x7f6948001d90]]: {
	b: 123,
	a: 123,
}
```

As can be seen, the string and number look the same.

We can either: 
1. Show the type
2. Just print quotes around strings
3. both

### LINKED ISSUE #63: [Feature Request] Show TID/PID in Debug mode
The server should show TIDs of threads in order to aid in production-debugging of high cpu usage.

It should look something like
```
Thread "MyThreadName" is TID 123456
```

This is easily done by adding it to the thread name registration stuff.

### LINKED ISSUE #65: [Feature Request] Provide health endpoint
**Is your feature request related to a problem? Please describe.**
No it is not related to a bug, it is a suggestion for improvement.

**Describe the solution you'd like**
Some kind of endpoint through which I can check the health of a running server (without evaluating the log).

**Describe alternatives you've considered**
Evaluating the log.
Query something to the query port?

**Additional context**
I am working on improving the docker container for beammp and what I am missing is a health status of running server. In case of a misconfiguration or similar it can happen that the server is running but in a faulty error state.

**Open questions**
Is there even an "error state" that the server can reach where the server process continues to run without aborting with an error code.

### LINKED ISSUE #66: [Feature Request] Enable macOS Toolchain Compatibility
**Is your feature request related to a problem? Please describe.**
Currently the 'BeamMP-Server' project will not compile on macOS Monterey with Apple Clang 12.0.
I assume this is a systemic issue and won't work across all macOS versions, since macOS is rarely a compile target
in C++ application development.

**Describe the solution you'd like**
Either a project that works with the macOS toolchain (Clang/Cmake) and compiles on Mac or a **docker** based build and test environment that includes all dependencies needed to build BeamMP-Server, as well as run and test it in the container.
(Keywords are automated testing and platform independence)

### PR DESCRIPTION
**Pull request by lionkor**
This replaces #32.

### CODE REVIEW

**Comment by Starystars67** [comment]
Getting excited for this now!

**Comment by lionkor** [comment]
> Getting excited for this now!

I'm almost done with reimplementing all old-lua features. This entire rewrite is also a redesign - so it's all quite clean now and I'm trying to make it so I don't have to touch it much to add anything.

**Comment by Starystars67** [comment]
> > Getting excited for this now!
> 
> I'm almost done with reimplementing all old-lua features. This entire rewrite is also a redesign - so it's all quite clean now and I'm trying to make it so I don't have to touch it much to add anything.

Sounds like a good plan to me. I suspect that there might be a influx of requested functions to be added once we release this and the event for it too.

**Comment by lionkor** [comment]
For sure. I already added a bunch of requested ones.

**Comment by Starystars67** [comment]
Is this ready to be merged yet?

**Comment by lionkor** [comment]
> Is this ready to be merged yet?

I want to get rid of major bugs first, that could take a little bit of time. Once the API is stable enough we can EA release.

**Comment by lionkor** [comment]
If you @Anonymous-275 can look over it & approve it, that'd be amazing!
Then I'll do some finishing touches for the release.

**Comment by lionkor** [comment]
I'm aware of conflicts, I'll resolve them myself once I have approval :)

**Review by Anonymous-275 — APPROVED** [review]
yes

**Comment by lionkor** [comment]
:tada: :tada: :tada: :tada: :tada: :tada:

**Comment by 20dka** [comment]
🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
