### PR TITLE
Introduce Sentry

### PR DESCRIPTION
**Pull request by lionkor**
Introduces Sentry for better diagnostics.

### CODE REVIEW

**Comment by lionkor** [comment]
Adds a new dependency, sentry-native, as a submodule, and curl as a dependency (again).

**Comment by lionkor** [comment]
Needs more testing and thorough code review before merge.

**Comment by lionkor** [comment]
Well, that was a pain and a half to get to compile. Anyways, it's ready to be tested on the backend servers, then we merge & pre-release for EA, then we push public.

**Comment by lionkor** [comment]
My Actions can't read the secret. This PR is on ice until then, dont merge

**Review by Starystars67 — APPROVED** [review]

**Comment by lionkor** [comment]
Rebased and squashed a few commits, will now merge if actions are good.

**Pull request merged**
