### PR TITLE
Added Tags Feature to the BeamMP Server. 

### PR DESCRIPTION
**Pull request by Starystars67**
This PR adds a tags functionality to the BeamMP server config and heartbeat.
The intended purpose of this is to enable better filtering on the server list based on keywords such as gamemode or roleplay.

### CODE REVIEW

**Comment by lionkor** [comment]
TOML has arrays, so this should probably be an array:
```
Tags = ["Tag1", "Tag2"]
```

**Comment by Starystars67** [comment]
Hi Lion, 

I have been thinking this one over over the last week and bit and I am thinking that though for us more technically capable people an array is the correct approach. 

BeamMP however is also used my people who are not as technically capable and I worry that a potential missing quote mark or comma in an array could cause the config to not be loaded and then raise new posts in support.

Happy to hear other sides on this though.

**Comment by lionkor** [comment]
Fair enough, it's definitely a more complicated syntax as a TOML array. What bothers me about this approach is that it's an undocumented syntax, the parser for which will be in the backend. In this case, the comment should probably explain the syntax, something like "Separate tags with commas, like so: Tag1,Tag2,Tag3" or something.
And then any tool parsing or writing to the config will have to also write a parser/serializer for it, so either way would be good to document it in the file itself.

Other than that, maybe the team can decide on some good default tags, because I can't think of any.

As for the windows compile error, that maybe a dependency issue, Anon might be able to help there.

**Comment by Starystars67** [comment]
> Fair enough, it's definitely a more complicated syntax as a TOML array. What bothers me about this approach is that it's an undocumented syntax, the parser for which will be in the backend. In this case, the comment should probably explain the syntax, something like "Separate tags with commas, like so: Tag1,Tag2,Tag3" or something. And then any tool parsing or writing to the config will have to also write a parser/serializer for it, so either way would be good to document it in the file itself.

Yep, that is what I did on line 106 in src/TConfig.cpp.
 
> Other than that, maybe the team can decide on some good default tags, because I can't think of any.

Indeed.

> As for the windows compile error, that maybe a dependency issue, Anon might be able to help there.

Will do. @Anonymous-275 :P

**Comment by lionkor** [comment]
Needs better or no default tags

**Comment by Starystars67** [comment]
> Needs better or no default tags

Done. Changed the default to Freeroam to match the majority of servers presently on the list.

**Comment by Starystars67** [comment]
Backend support for this is already implemented.

**Comment by lionkor** [comment]
Blocked by #227

**Comment by lionkor** [comment]
Made the tags pretty-print in the debug view

image

image

**Review by lionkor — APPROVED** [review]

**Pull request merged**
