### PR TITLE
Replace networking with boost::asio (synchronous)

### PR DESCRIPTION
**Pull request by lionkor**
- replaced all networking with boost::asio abstractions
- rewrote the SetStatus(), GetStatus() crap (now IsDisconnected() and Disconnect() with reason)
- fixed bug related to ghost players / ghost cars
- handles packets as binary for the most part (vector<uint8_t> instead of string) to fix various issues

### CODE REVIEW

**Comment by lionkor** [comment]
Motivation:

The old networking was written by hand, a long time ago, and uses #ifdefs and similar magic to get winsock and posix sockets to work.

The old networking is, from my experience maintaining this for a while now:
- difficult to reason about, due to shared state (GetStatus, SetStatus)
- difficult to debug, as all platforms are different

Further, boost::asio is a very cheap abstraction layer, which also makes ipv6 support *trivial* in the future.
Another benefit is that boost::asio is documented(ish) and tested properly, whereas the previous networking code was neither documented, nor tested, or in any way properly designed.

This PR does **NOT** fix inherent design problems with the networking, those are still to-fix. Examples:
- inconsistent and undocumented packet codes (no, code is not documentation, not when its 5 functions away in some random callstack)
- strings used for packets, which breaks every time there is a `\0` byte (among other issues)
- download sockets as global(ish) state

**Comment by lionkor** [comment]
To be clear: I do not have any problems understanding or reasoning about the networking code, before or after, but this makes it easier for new contributors (who we need), and makes bugs more difficult to introduce.

**Comment by lionkor** [comment]
A test server with this version running on it has been at the top of the server list without issues for 220 hours, at this point. The log is 1.4 GB, because it's in TRACE + DEBUG mode, but you can believe me that there are no unexpected errors or warnings, or other issues reported.

**Review by Anonymous-275 — APPROVED** [review]
Clean work, Looking forward to a solid networking system.

**Comment by lionkor** [comment]
Merging, the windows actions issue seems unrelated (vcpkg update)

**Pull request merged**
