### PR TITLE
Documents for dependencies on macos

### PR DESCRIPTION
**Pull request by mio-19**

### CODE REVIEW

**Comment by mio-19** [comment]
This pr requires https://github.com/BeamMP/BeamMP-Server/pull/110

**Comment by mio-19** [comment]
[BeamMP-Server.zip](https://github.com/BeamMP/BeamMP-Server/files/9007594/BeamMP-Server.zip)
v3.0.1 built for Apple Silicon

**Comment by lionkor** [comment]
Thank you very much for your contribution!

With your permission, I would merge the lionkor/commandline patch into commandline upstream, too.

I'll get someone with a MacOS device to test this, and then we'll merge it. So far the code looks good to me ;)

**Review by lionkor — COMMENTED** [review]
Is there any reason you recommend to use gcc here? Latest clang shipped on MacOS should compile it just fine, considering its C++17. Is this just a preference, or to keep a consistent version?

**Comment by mio-19** [comment]
>  Is this just a preference, or to keep a consistent version?

It is just a preference

**Comment by mio-19** [comment]
> With your permission, I would merge the lionkor/commandline patch into commandline upstream, too.

I opened a pr https://github.com/lionkor/commandline/pull/24

**Comment by mio-19** [comment]
> Is there any reason you recommend to use gcc here? Latest clang shipped on MacOS should compile it just fine, considering its C++17. Is this just a preference, or to keep a consistent version?

Actually it doesn't compile with gcc. I removed the section

**Comment by lionkor** [comment]
On it, sorry for the long wait

**Review by lionkor — APPROVED** [review]
lgtm

**Pull request merged**
