### PR TITLE
Switch to TOML Config File

### PR DESCRIPTION
**Pull request by lionkor**
These commits switch from the cfg/json config to a [TOML](https://toml.io) format.

The base format now looks like this:

```toml
# This is the BeamMP-Server config file.
# Help & Documentation: `https://wiki.beammp.com/en/home/server-maintenance`
# IMPORTANT: Fill in the AuthKey with the key you got from `https://beammp.com/k/dashboard` on the left under "Keys"
[General]
AuthKey = ''
Debug = false
Description = 'BeamMP Default Description'
Map = '/levels/gridmap/info.json'
MaxCars = 1
MaxPlayers = 10
Name = 'BeamMP Server'
Port = 30814
Private = true
ResourceFolder = 'Resources'
```

### CODE REVIEW

**Comment by lionkor** [comment]
PR'ed so we can pull it into whatever release we want, feel free to merge whenever

**Comment by lionkor** [comment]
Reminder we also need to link to https://wiki.beammp.com/en/home/server-maintenance somewhere, once we publish this :)

**Comment by Starystars67** [comment]
~Can you have comments in your new config file?~
~If so put a comment at the top and then link the wiki page you mentioned above?~

Reread the content above and realise that I misunderstood. You mean to put it in the release notes?

**Comment by lionkor** [comment]
I meant putting that page on the side nav bar in the wiki

**Comment by lionkor** [comment]
merged by request of @Anonymous-275

**Pull request merged**
