### PR TITLE
Fix GitHub Actions not downloading the latest tests to run them

### LINKED ISSUE #219: Run-tests actions not downloading cross-workflow artifacts
Currently, the github action for running tests doesn't run, because somehow the download-artifact action doesn't allow downloading artifacts from a different workflow.. or something. https://github.com/actions/download-artifact/issues/3. Literally the only thing you'd use this for, but whatever.

Fix by using https://github.com/dawidd6/action-download-artifact

Edit: Might be a different issue!

### PR DESCRIPTION
**Pull request by lionkor**
Closes #219

### CODE REVIEW

**Review by Starystars67 — COMMENTED** [review]
Reviewing this I notice that you removed the debian and ubuntu tests and only now have the test for ubuntu. 

Was this intended? If so how are debian builds and tests now done?

**Comment by lionkor** [comment]
No idea why the diff looks so weird, it's very odd. But if you go to the actual file, it has tests on both, unless im missing something there

**Comment by Starystars67** [comment]
Indeed I see that now when viewing the complete file.

To be clear, I understand that the tests are a part of the build process now correct?

**Review by Starystars67 — APPROVED** [review]

**Comment by lionkor** [comment]
Yes, the builds will fail if the tests fail -- that's not *great*, but really, if the tests fail, something is fucked royally. The unit tests currently unit test only some small parts, but still!

**Pull request merged**
