### PR TITLE
Fix `MP.GetPositionRaw`

### LINKED ISSUE #167: [Bug] MP.GetPositionRaw() returns <nil> Vehicle not found for player_id greater than 9
**Fill out general information**
OS: Windows 11
BeamMP-Server Version: 3.1.1 Windows Public Release

**Describe the bug**
Use of `MP.GetPositionRaw()` for valid `player_id`s greater than 9  and any valid vehicle_id returns `<nil> Vehicle not found`

**To Reproduce**
1. Have 11 or more players on the server, all fully synced. Player 11, `player_id = 10`,  or greater spawns at least one vehicle
2. In the server console, `print(MP.GetPositionRaw(10, 0))` returns `<nil> Vehicle not found`
3. `MP.GetPositionRaw(11, 0)` returns `<nil> Vehicle not found`
4. et cetera

**Expected behavior**
`MP.GetPositionRaw()` should return the expected table for a valid `player_id`

**Logs**
```
[13/01/23 17:49:35] [LUA] [Cobalt] On Player Join: 10
[13/01/23 17:49:35] [INFO] Wacky0_o is now synced!
> lua
Attached to Lua. For help, type `:help`. To detach, type `:exit`
[13/01/23 17:49:49] [LUA] [Cobalt] Wacky0_o spawned a 'midtruck' (10-0)
lua> print(MP.GetPositionRaw(10, 0))
[13/01/23 17:50:02] [LUA] <nil>	Vehicle not found	
```

**Additional context**
NuclearKnight00#4892 made this bug known in the discord.

### PR DESCRIPTION
**Pull request by lionkor**

### CODE REVIEW

**Comment by Starystars67** [comment]
Is this all set and ready for review?

**Comment by lionkor** [comment]
Yes, needs review and testing

**Comment by lionkor** [comment]
Ok tested it, doesn't work. A few other things also break with pid > 9, investigating.

**Comment by lionkor** [comment]
Ok works, needs a quick sanity-test and review

**Review by snepsnepsnep — APPROVED** [review]

**Pull request merged**
